### ISSUE TITLE
找不到入口退出，Xpath失效

### ISSUE THREAD

**Issue by Kwaiyu** [testerzhang/taobaomiao#2]
![image](https://user-images.githubusercontent.com/28617728/138308137-a217f385-b7a7-478e-88b4-b27c85482744.png)

于是延长了等待时间到10秒，界面已经加载出来了还是找不到入口

于是自己定位了下发现这个Xpath 不能点击了
![image](https://user-images.githubusercontent.com/28617728/138308433-f1622df8-7855-4d64-878d-83321e508bf6.png)

![image](https://user-images.githubusercontent.com/28617728/138308520-1a7cf85e-e967-4808-9893-0342ed6fcaf0.png)

求助大佬有没有其他的定位方式可点击
或者说直接抓包找活动链接进去？

**Comment by testerzhang** [comment]
你的界面跟我不一样，中间我是四个入口。
第1种：首页xml不复杂，中间的xml直接展开，点击找到对应的位置，看index是多少。
第2种：根据bounds的坐标(如：[26,1025][540,1290]），然后不使用xpath，使用这个方法      
 self.driver.tap([(26, 1025), (540, 1290)], 100)
